"""Generate a realistic volume of tickets, for benchmarking queries locally.

Rows go in through one INSERT ... SELECT generate_series(...) instead of
Model.objects.bulk_create(): bulk_create runs the fields' pre_save hooks, and
created_at's auto_now_add would overwrite every timestamp with "now", leaving
no spread over time to query against. Building the rows inside Postgres also
keeps a few hundred thousand tickets down to under a minute.

Safe to re-run: organizations and users are reused, tickets are appended.
"""

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import connection, transaction

from apps.accounts.models import Organization, User
from apps.tickets.models import Category, Priority, SLAPolicy, Ticket

CATEGORY_NAMES = ["Billing", "Bug report", "Feature request", "Account access", "How-to", "Other"]
SLA_RESOLUTION_MINUTES = {
    Priority.URGENT: 4 * 60,
    Priority.HIGH: 24 * 60,
    Priority.MEDIUM: 72 * 60,
    Priority.LOW: 7 * 24 * 60,
}
AGENTS_PER_ORG = 5
CUSTOMERS_PER_ORG = 40

# MATERIALIZED pins each row's random() rolls: the later steps read the same
# roll several times (status decides resolved_at and assignee), so the planner
# must not re-evaluate them.
SEED_SQL = """
WITH rolled AS MATERIALIZED (
    SELECT
        n,
        now() - random() * interval '180 days' AS created_at,
        random() AS status_roll,
        random() AS priority_roll,
        random() AS assignee_roll,
        random() AS work_roll
    FROM generate_series(1, %(count)s) AS n
),
shaped AS (
    SELECT
        n, created_at, assignee_roll, work_roll,
        CASE
            WHEN status_roll < 0.55 THEN 'closed'
            WHEN status_roll < 0.80 THEN 'resolved'
            WHEN status_roll < 0.92 THEN 'open'
            ELSE 'pending'
        END AS status,
        CASE
            WHEN priority_roll < 0.15 THEN 'low'
            WHEN priority_roll < 0.65 THEN 'medium'
            WHEN priority_roll < 0.90 THEN 'high'
            ELSE 'urgent'
        END AS priority
    FROM rolled
)
INSERT INTO {table} (
    id, created_at, updated_at, organization_id, category_id, requester_id,
    assignee_id, subject, description, status, priority, due_at, resolved_at
)
SELECT
    gen_random_uuid(),
    created_at,
    CASE WHEN status IN ('resolved', 'closed')
         THEN LEAST(now(), created_at + work_roll * interval '5 days')
         ELSE created_at END,
    %(organization)s,
    (%(categories)s::uuid[])[1 + floor(random() * cardinality(%(categories)s::uuid[]))::int],
    (%(customers)s::bigint[])[1 + floor(random() * cardinality(%(customers)s::bigint[]))::int],
    CASE WHEN status = 'open' AND assignee_roll < 0.2
         THEN NULL
         ELSE (%(agents)s::bigint[])[1 + floor(random() * cardinality(%(agents)s::bigint[]))::int]
    END,
    'Seeded ticket #' || n,
    'Generated by seed_tickets for query benchmarking.',
    status,
    priority,
    created_at + CASE priority
        WHEN 'urgent' THEN interval '4 hours'
        WHEN 'high' THEN interval '1 day'
        WHEN 'medium' THEN interval '3 days'
        ELSE interval '7 days'
    END,
    CASE WHEN status IN ('resolved', 'closed')
         THEN LEAST(now(), created_at + work_roll * interval '5 days') END
FROM shaped
"""


class Command(BaseCommand):
    help = "Create demo organizations and bulk-insert tickets to benchmark queries against."

    def add_arguments(self, parser):
        parser.add_argument("--orgs", type=int, default=3, help="Organizations to create or reuse.")
        parser.add_argument(
            "--tickets-per-org", type=int, default=100_000, help="Tickets to add to each one."
        )

    def handle(self, *args, **options):
        if not settings.DEBUG:
            raise CommandError("Refusing to seed data while DEBUG is off.")

        for number in range(1, options["orgs"] + 1):
            with transaction.atomic():
                organization = self._prepare_organization(number)
                self._insert_tickets(organization, options["tickets_per_org"])
            self.stdout.write(f"{organization.slug}: +{options['tickets_per_org']} tickets")

        # Fresh statistics, so EXPLAIN reflects the data that was just loaded.
        table = connection.ops.quote_name(Ticket._meta.db_table)
        with connection.cursor() as cursor:
            cursor.execute(f"ANALYZE {table}")
        self.stdout.write(self.style.SUCCESS(f"Done. {Ticket.objects.count()} tickets in total."))

    def _prepare_organization(self, number):
        slug = f"demo-org-{number}"
        organization, _ = Organization.objects.get_or_create(
            slug=slug, defaults={"name": f"Demo Organization {number}"}
        )
        self._ensure_user(organization, f"{slug}-owner", User.Role.OWNER)
        for index in range(1, AGENTS_PER_ORG + 1):
            self._ensure_user(organization, f"{slug}-agent-{index}", User.Role.AGENT)
        for index in range(1, CUSTOMERS_PER_ORG + 1):
            self._ensure_user(organization, f"{slug}-customer-{index}", User.Role.CUSTOMER)
        for name in CATEGORY_NAMES:
            Category.objects.get_or_create(organization=organization, name=name)
        for priority, minutes in SLA_RESOLUTION_MINUTES.items():
            SLAPolicy.objects.get_or_create(
                organization=organization,
                priority=priority,
                defaults={
                    "name": f"{priority.label} SLA",
                    "response_time_minutes": minutes // 4,
                    "resolution_time_minutes": minutes,
                },
            )
        return organization

    @staticmethod
    def _ensure_user(organization, username, role):
        # No password: these accounts exist only to own and be assigned tickets.
        if not User.objects.filter(username=username).exists():
            User.objects.create_user(username=username, organization=organization, role=role)

    @staticmethod
    def _insert_tickets(organization, count):
        def ids(role):
            return list(
                User.objects.filter(organization=organization, role=role).values_list(
                    "id", flat=True
                )
            )

        params = {
            "count": count,
            "organization": organization.id,
            "categories": list(organization.categories.values_list("id", flat=True)),
            "customers": ids(User.Role.CUSTOMER),
            "agents": ids(User.Role.AGENT),
        }
        sql = SEED_SQL.format(table=connection.ops.quote_name(Ticket._meta.db_table))
        with connection.cursor() as cursor:
            cursor.execute(sql, params)
