# Generated by Django 6.1.1 on 2026-09-17 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_apikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "name"), name="unique_category_name_per_org"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "response_time_minutes",
                    models.PositiveIntegerField(
                        help_text="How quickly an agent must first respond, in minutes."
                    ),
                ),
                (
                    "resolution_time_minutes",
                    models.PositiveIntegerField(
                        help_text="How quickly the ticket must be resolved, in minutes."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_policies",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SLA policies",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "priority"), name="unique_sla_policy_per_priority"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "name"), name="unique_tag_name_per_org"
                    )
                ],
            },
        ),
    ]
