# Generated by Django 6.1.1 on 2026-09-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="slapolicy",
            options={"ordering": ["priority"], "verbose_name_plural": "SLA policies"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
    ]
