# Generated by Django 6.1.1 on 2026-09-18 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_apikey"),
        ("tickets", "0005_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="sla_breached_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set once, the first time the SLA scanner detects this ticket passed its due_at — guards against re-notifying on every scan.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["due_at", "sla_breached_at"], name="ticket_due_breached_idx"
            ),
        ),
    ]
